language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run react-test npm test a -- --watchAll=false --coverage

after_success:
    # Build images
    - docker build -t mindzoom/multi-client ./client
    - docker build -t mindzoom/multi-api ./api
    - docker build -t mindzoom/multi-worker ./worker
    - docker build -t mindzoom/multi-nginx ./nginx

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push images to the Docker Hub
    - docker push mindzoom/multi-client
    - docker push mindzoom/multi-api
    - docker push mindzoom/multi-worker
    - docker push mindzoom/multi-nginx

deploy:
    prodiver: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-964176841427'
    bucket_path: 'docker-multi'
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
