version: "3"

services: 
    postgres:
        image: 'postgres:13.0'
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
    redis:
        image: 'redis:6.0.9'
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '8080:80'
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./api
        volumes: 
            - /app/node_modules
            - ./api:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_DATABASE=postgres
            - PG_USER=admin
            - PG_PASSWORD=password
        depends_on:
            - postgres
            - redis

    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis